### ISSUE TITLE
I am learning Zcash how it work by reading code,but this codes seems does not work.

### ISSUE THREAD

**Issue by liuxurong** [str4d/zcash-pow#10]
./print-soln.py 200 9 "04000000e54c27544050668f272ec3b460e1cde745c6b21239a81dae637fde4704000000844bc0c55696ef9920eeda11c1eb41b0c2e7324b46cc2e7aa0c2aa7736448d7a000000000000000000000000000000000000000000000000000000000000000068241a587e7e061d250e000000000000010000000000000000000000000000000000000000000000"

Traceback (most recent call last):
File "./print-soln.py", line 60, in
print_hashes(*generate_hashes(args.n, args.k, unhexlify(args.header)))
File "./print-soln.py", line 36, in generate_hashes
numIndices = ord(header[140]) if ord(header[140]) < 256 else struct.unpack('<H', header[141:143])
IndexError: string index out of range

**Comment by liuxurong** [comment]
collision_length = n/(k+1)
hash_length = (k+1)*((collision_length+7)//8)

collision_length = 20

(9 + 1) * 3  

hash_length = 30 ???????????????????????????????????????????????????????????????

**Comment by str4d** [comment]
Hi! I just fixed `print-soln.py`, so you can try it out now with blocks from the live network :smile: Please re-open this issue if you still have problems!
