### ISSUE TITLE
Implementation still in sync with zcash's C++ one?

### ISSUE THREAD

**Issue by maltese** [str4d/zcash-pow#5]
Hello,

is this implementation still in sync with the one used by the official C++ version? ( https://github.com/zcash/zcash )

Or more specifically: do the test vectors lead to the same solutions?

Am looking to help the project and I wanted to start understanding equihash using the python version first.

**Comment by str4d** [comment]
Yes, the test vectors in this repo are the same as in the C++ repo (you can run `./test-pow.py` and see; look in `src/test/equihash_tests.cpp` in the C++ repo for the equivalent tests there). However, I have not yet updated this repo to work with the latest parameters; I have opened #6 for that.

**Comment by maltese** [comment]
Nice. Thanks.
