### ISSUE TITLE
Digest length used in print-soln

### ISSUE THREAD

**Issue by 4zec** [str4d/zcash-pow#8]
I think `print-soln.py` is not setting the blake 2b digest length correctly. It is using `n/8` (=25) on [line 34](https://github.com/str4d/zcash-pow/blob/master/print-soln.py#L34) where other code, especially `test-pow.py` is using `(512/n)*n/8` (=50). As discussed in the zcash paper, this will give different hashes because the digest length is captured into the blake2b personalization.

**Comment by vattay** [comment]
I think this is due to the way the POW implementations use blake2 for their hash generation vs the print solution script. If you look at [pow.py:line71](https://github.com/str4d/zcash-pow/blob/master/pow.py#L71) it creates a long hash and cuts it up in to pieces, 512/n pieces. I'm not sure if this is an optimization (it does reduce the number of hash calls).

**Comment by 4zec** [comment]
Yes, I think you are correct w.r.t how a 50-byte digest is used for two consecutive index values, but regardless, the blake2b setup will not be compatible. Overall, it seems like `print-soln` needs some updates to be useful.

**Comment by str4d** [comment]
Yes, I didn't get around to updating print-soln at all when I updated the rest of the code to match zcashd :stuck_out_tongue_closed_eyes:

**Comment by liuxurong** [comment]
./print-soln.py 200 9 "04000000e54c27544050668f272ec3b460e1cde745c6b21239a81dae637fde4704000000844bc0c55696ef9920eeda11c1eb41b0c2e7324b46cc2e7aa0c2aa7736448d7a000000000000000000000000000000000000000000000000000000000000000068241a587e7e061d250e000000000000010000000000000000000000000000000000000000000000"

Traceback (most recent call last):
  File "./print-soln.py", line 60, in <module>
    print_hashes(*generate_hashes(args.n, args.k, unhexlify(args.header)))
  File "./print-soln.py", line 36, in generate_hashes
    numIndices = ord(header[140]) if ord(header[140]) < 256 else struct.unpack('<H', header[141:143])
IndexError: string index out of range

**Comment by str4d** [comment]
Finally finished and pushed this update, so you can now use `print-soln.py` to inspect the solutions of blocks from the live network :smile:
