### ISSUE TITLE
Whats the expand_array function for?

### ISSUE THREAD

**Issue by Ulysseus** [str4d/zcash-pow#9]
I took it out of lines 70-71 in pow.py
Ran test-pow.py and it works just fine??

**Comment by str4d** [comment]
`expand_array` is necessary for Equihash parameter choices where the collision bit length is not an integer number of bytes. What it does is expand every collision area to fill an integer number of bytes. For the regtest parameters (96, 5) the collision length is 16 bits (2 bytes), so `expand_array` does nothing. For the mainnet parameters (200, 9) the collision length is 20 bits (2.5 bytes), so `expand_array` expands each collision area out to 24 bits (3 bytes).
